name: Build and test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add Vipps NuGet Source
        run: dotnet nuget update source GitHub_Nuget --store-password-in-clear-text -u USERNAME -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: dotnet build --configuration Release ./dotnet/VippsMobilePay.Changefeed

      - name: Test
        run: dotnet test --configuration Release ./dotnet/VippsMobilePay.Changefeed
